---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: datahubid/web:latest
        imagePullPolicy: Always
        name: web
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  ports:
  - nodePort: 32323
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort